// <auto-generated />
using EfcRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcRepositories.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20251119161737_AddPostUserCommentEntities")]
    partial class AddPostUserCommentEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("EfcRepositories.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserCommentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommentsId");

                    b.HasIndex("UserCommentsId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("EfcRepositories.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostsId");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("EfcRepositories.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EfcRepositories.Comment", b =>
                {
                    b.HasOne("EfcRepositories.Post", "Comments")
                        .WithMany("Comments")
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfcRepositories.User", "UserComments")
                        .WithMany("UserComments")
                        .HasForeignKey("UserCommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("UserComments");
                });

            modelBuilder.Entity("EfcRepositories.Post", b =>
                {
                    b.HasOne("EfcRepositories.User", "Posts")
                        .WithMany("Posts")
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EfcRepositories.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("EfcRepositories.User", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("UserComments");
                });
#pragma warning restore 612, 618
        }
    }
}
